export default {
  login: "kentcdodds",
  id: 1500684,
  node_id: "MDQ6VXNlcjE1MDA2ODQ=",
  avatar_url: "https://avatars0.githubusercontent.com/u/1500684?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/kentcdodds",
  html_url: "https://github.com/kentcdodds",
  followers_url: "https://api.github.com/users/kentcdodds/followers",
  following_url: "https://api.github.com/users/kentcdodds/following{/other_user}",
  gists_url: "https://api.github.com/users/kentcdodds/gists{/gist_id}",
  starred_url: "https://api.github.com/users/kentcdodds/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/kentcdodds/subscriptions",
  organizations_url: "https://api.github.com/users/kentcdodds/orgs",
  repos_url: "https://api.github.com/users/kentcdodds/repos",
  events_url: "https://api.github.com/users/kentcdodds/events{/privacy}",
  received_events_url: "https://api.github.com/users/kentcdodds/received_events",
  type: "User",
  site_admin: false,
  name: "Kent C. Dodds",
  company: "@kentcdodds",
  blog: "https://kentcdodds.com",
  location: "Salt Lake City, Utah, USA",
  email: null,
  hireable: null,
  bio: "Making people's lives better with software · Husband, Father, Latter-day Saint, Teacher, OSS, GDE · testingjavascript.com ",
  twitter_username: null,
  public_repos: 572,
  public_gists: 204,
  followers: 14393,
  following: 41,
  created_at: "2012-03-04T22:32:01Z",
  updated_at: "2020-07-25T18:03:46Z"
  };
